/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import keeptoo.Drag;

/**
 *
 * @author TsundereMoe
 */
public class LoginRegister extends javax.swing.JFrame {

    /**
     * Creates new form LoginRegister
     */
    
    public LoginRegister() {
        initComponents();
    }
    public static void initSetting(){
        try {
            //render and change icon of a button
            LoginRegister loginForm = new LoginRegister();
            loginForm.setBackground(new Color(0,0,0,0));
            ImageIcon icon= new ImageIcon(LoginRegister.class.getResource("logout.png"));
            Image img = icon.getImage();
            Image newimg = img.getScaledInstance(0x32, 30,  java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newimg);
            loginForm.btnLogout.setIcon(newIcon);
            //change font of a swing element
            InputStream is = LoginRegister.class.getResourceAsStream("Vanessas Valentine.otf");
            InputStream is1 = LoginRegister.class.getResourceAsStream("Lavina 4F.otf");
            InputStream is2 = LoginRegister.class.getResourceAsStream("FVF Fernando 08.ttf");
            InputStream is3 = LoginRegister.class.getResourceAsStream("Lavina 4F.otf");
            InputStream is4 = LoginRegister.class.getResourceAsStream("VL COCO.OTF");
           // InputStream is5 = LoginRegister.class.getResourceAsStream("FS Endless Sorrow Regular.otf");
            
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
            Font font1 = Font.createFont(Font.TRUETYPE_FONT, is1);
            Font font2 = Font.createFont(Font.TRUETYPE_FONT, is2);
            Font font3 = Font.createFont(Font.TRUETYPE_FONT, is3);
            Font font4 = Font.createFont(Font.TRUETYPE_FONT, is4);
           // Font font5 = Font.createFont(Font.TRUETYPE_FONT, is5);
            
            loginForm.lblTitle1.setFont(font.deriveFont(70f));
            loginForm.lblTitle2.setFont(font1.deriveFont(30f));
            loginForm.lblID.setFont(font2.deriveFont(14f));
            loginForm.lblPassword.setFont(font2.deriveFont(14f));
            loginForm.txtID.setFont(font3.deriveFont(13f));
            loginForm.txtPassword.setFont(font3.deriveFont(14f));
            loginForm.btnLogin.setFont(font4.deriveFont(30f));
            loginForm.btnRegister.setFont(font4.deriveFont(30f));
            loginForm.btnHidePass.setFont(font2.deriveFont(9f));
            //show frame
            loginForm.setVisible(true);
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(LoginRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new keeptoo.KGradientPanel();
        btnRegister = new keeptoo.KButton();
        btnLogout = new keeptoo.KButton();
        txtID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        btnLogin = new keeptoo.KButton();
        lblTitle1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnHidePass = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("loginRegisterForm"); // NOI18N
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        backGround.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        backGround.setkBorderRadius(100);
        backGround.setkEndColor(new java.awt.Color(255, 153, 153));
        backGround.setkStartColor(new java.awt.Color(51, 255, 255));
        backGround.setOpaque(false);

        btnRegister.setBorder(null);
        btnRegister.setForeground(new java.awt.Color(102, 255, 102));
        btnRegister.setText("Register");
        btnRegister.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 11)); // NOI18N
        btnRegister.setkBorderRadius(200);
        btnRegister.setkForeGround(new java.awt.Color(255, 255, 153));
        btnRegister.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnRegister.setkStartColor(new java.awt.Color(255, 102, 153));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 153, 153));
        btnLogout.setBorder(null);
        btnLogout.setForeground(new java.awt.Color(15, 255, 0));
        btnLogout.setkBackGroundColor(new java.awt.Color(255, 153, 153));
        btnLogout.setkBorderRadius(-1);
        btnLogout.setkEndColor(new java.awt.Color(255, 153, 153));
        btnLogout.setkFillButton(false);
        btnLogout.setkForeGround(new java.awt.Color(255, 153, 153));
        btnLogout.setkHoverColor(new java.awt.Color(255, 153, 153));
        btnLogout.setkHoverEndColor(new java.awt.Color(255, 153, 153));
        btnLogout.setkHoverForeGround(new java.awt.Color(255, 153, 153));
        btnLogout.setkHoverStartColor(new java.awt.Color(255, 153, 153));
        btnLogout.setkIndicatorColor(new java.awt.Color(15, 255, 0));
        btnLogout.setkIndicatorThickness(0);
        btnLogout.setkPressedColor(new java.awt.Color(255, 153, 153));
        btnLogout.setkSelectedColor(new java.awt.Color(255, 153, 153));
        btnLogout.setkStartColor(new java.awt.Color(255, 153, 153));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtID.setBackground(new java.awt.Color(153, 255, 153));
        txtID.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        txtID.setForeground(new java.awt.Color(51, 0, 51));

        lblID.setForeground(new java.awt.Color(51, 0, 255));
        lblID.setText("ID");

        lblPassword.setForeground(new java.awt.Color(51, 0, 255));
        lblPassword.setText("Password");
        lblPassword.setToolTipText("6-14 characters");

        lblTitle2.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 0, 0));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setLabelFor(this);
        lblTitle2.setText(" Chat");
        lblTitle2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnLogin.setBorder(null);
        btnLogin.setForeground(new java.awt.Color(102, 255, 102));
        btnLogin.setText("Login");
        btnLogin.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 11)); // NOI18N
        btnLogin.setkBorderRadius(200);
        btnLogin.setkForeGround(new java.awt.Color(255, 255, 153));
        btnLogin.setkHoverColor(new java.awt.Color(255, 0, 255));
        btnLogin.setkHoverEndColor(new java.awt.Color(204, 255, 255));
        btnLogin.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnLogin.setkHoverStartColor(new java.awt.Color(204, 255, 204));
        btnLogin.setkStartColor(new java.awt.Color(255, 102, 153));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(102, 0, 102));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setLabelFor(this);
        lblTitle1.setText("Coding");
        lblTitle1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txtPassword.setBackground(new java.awt.Color(153, 255, 153));
        txtPassword.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 0, 51));

        btnHidePass.setBorder(null);
        btnHidePass.setForeground(new java.awt.Color(102, 255, 102));
        btnHidePass.setText("Unhide");
        btnHidePass.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 11)); // NOI18N
        btnHidePass.setkBorderRadius(200);
        btnHidePass.setkForeGround(new java.awt.Color(255, 255, 153));
        btnHidePass.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnHidePass.setkHoverStartColor(new java.awt.Color(204, 255, 204));
        btnHidePass.setkStartColor(new java.awt.Color(255, 102, 153));
        btnHidePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHidePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backGroundLayout = new javax.swing.GroupLayout(backGround);
        backGround.setLayout(backGroundLayout);
        backGroundLayout.setHorizontalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backGroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID)
                    .addComponent(lblPassword))
                .addGap(54, 54, 54)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backGroundLayout.createSequentialGroup()
                                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHidePass, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );
        backGroundLayout.setVerticalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                        .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                        .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID))
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblPassword))
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btnHidePass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backGround, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        new Drag(this.rootPane).onPress(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        new Drag(this.rootPane).moveWindow(evt);
        
    }//GEN-LAST:event_formMouseDragged

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        //add ID and Password to Socket and database
        
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // get ID and password input to check with Socket and database
        Dashboard dashBoard = new Dashboard();
        dashBoard.setVisible(true);
        dashBoard.toFront();
        
        
    }//GEN-LAST:event_btnLoginActionPerformed
    int count=0;
    private void btnHidePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHidePassActionPerformed
        // unhide and hide password with count
        if (count % 2==0) {
            this.txtPassword.setEchoChar((char)0);
        } else {
            this.txtPassword.setEchoChar('*');
        }
        count++;
    }//GEN-LAST:event_btnHidePassActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                initSetting();
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel backGround;
    private keeptoo.KButton btnHidePass;
    private keeptoo.KButton btnLogin;
    private keeptoo.KButton btnLogout;
    private keeptoo.KButton btnRegister;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
